### PR TITLE
Respect Server response Cache related headers.

### PR DESCRIPTION
**Pull request by valdemon**
- done with the usage of the opinionated https://www.npmjs.com/package/http-cache-semantics
- adopted tests
- additional test cases
- support for client request cache related headers
- README.md updated

### CODE REVIEW

**Comment by jpodwys** [comment]
Hi thank you for this PR! I apologize for my late response. When I wrote this library, I had two primary goals for code maintenance:

1. Keep the download size as small as possible
2. Keep the barrier to entry as low as possible

While this PR adds important convenience, it also 1) significantly increases the download size and 2) increases the barrier to entry by requiring that a transpiler be used for browsers lacking ES6 support.

If I were to merge this PR, I would need to cut a breaking release due to the new requirement for a transpilier (cutting a breaking release does not bother me). However, before talking more about merging this PR, I'd like to discuss the possibility of making this PR into either a superagent plugin that coexists with superagent-cache-plugin, or perhaps a plugin that can be used to directly modify superagent-cache-plugin. I know that sounds odd, but it would give users the freedom to choose whether they want to download the extra code at all--I don't like the idea of forcing all users to download code they're unlikely to use unless it's only a marginal increase in download size.

What are your thoughts?

**Comment by jpodwys** [comment]
Closing due to lack of response.

**Comment by jpodwys** [comment]
@valdemon At the time you originally submitted this PR I was overly hesitant to add third-party libraries. I was wrong in that regard. You've done excellent work here and I'd like to merge your fork. I'll go ahead and work on resolving merge conflicts. Please let me know if you have any thoughts.

A number of people have requested this feature, the latest of which can be found [here](https://github.com/jpodwys/superagent-cache-plugin/issues/11).

**Comment by valdemon** [comment]
Hi @jpodwys cool to hear that!
I'm not with Finanzcheck.de any more though, what means I've lost the direct control over the PR branch.
Please go ahead and if you'd have any issues with the PR just comment here. It's been a while since I committed this but at least I can try to support you ;)

**Comment by hottehead** [comment]
Hey, Im the latest requester for this. I scanned the fork and the PR. If I can help somehow let me know.

**Comment by jpodwys** [comment]
@valdemon @hottehead I've merged this and published it to NPM as `3.0.0-beta.1`. I want to have a bit more time dive deep on a couple of things as well as updating some items in the readme before releasing as `3.0.0` but I didn't think that should stop people from trying it out!

I'd love to port these changes over to [superagent-cache](https://github.com/jpodwys/superagent-cache) sometime soon as well. Not sure when I'll have time to work on that right now, though.

@valdemon thank you again for these changes! @hottehead thanks for the push to merge this in.

**Pull request merged**
